### ISSUE TITLE
which program open this source code

### ISSUE THREAD

**Issue by newwiidbn** [chinyan/Genetic-Algorithm-based-Sudoku-Solver#1]
how open Performance Graph like this
 https://github.com/chinyan/Genetic-Algorithm-based-Sudoku-Solver

**Comment by chinyan** [comment]
Performance was manually tabulated and plotted on Excel.

**Comment by chinyan** [comment]
@newwiidbn Run Sudoku.py to start UI. The performance graph was manually tabulated and plotted using Excel.
